Documento de metodologias
Requisitos-de-Software/2021.2-AntennaPod pull request #23
Opened 2022-02-19 02:09 UTC by Thais-ra

2022-02-19 16:19 UTC, yudi-azvd commented on docs/headmap.md
> +# Headmap
Acho que o nome do arquivo deve ser `heatmap.md`, com "t". Heat de calor.

2022-02-19 16:27 UTC, yudi-azvd commented on mkdocs.yml
> +      - 100 Pila: priorizacao.md
```
  - Resultado: elicitacao/resultado.md
```

2022-02-19 16:28 UTC, yudi-azvd requested changes
Só rever as sugestões comentadas

2022-02-19 16:29 UTC, yudi-azvd commented on mkdocs.yml
> +      - 100 Pila: priorizacao.md
esse `elicitacao/resultado.md` existe na minha branch

2022-02-20 01:22 UTC, AmandaNbr approved these changes

2022-02-20 01:58 UTC, yudi-azvd approved these changes

2022-02-21 01:30 UTC, merged