Documentation#31/atas de reuniao
Requisitos-de-Software/2021.2-AntennaPod pull request #32
Opened 2022-02-24 23:14 UTC by Thais-ra

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
- [x] Documentação atualizada

### Descrição
Criação de atas de reunião.

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/Requisitos-de-Software/2021.2-AntennaPod/pulls) para a mesma atualização/alteração?
- [x] As mudanças seguem as políticas de [commit](https://github.com/Requisitos-de-Software/2021.2-AntennaPod/blob/main/docs/contribuicao/commits.md) e [branch](https://github.com/Requisitos-de-Software/2021.2-AntennaPod/blob/main/docs/contribuicao/branches.md)
- [ ] Todos os membros estão de acordo com a atualização

2022-02-24 23:20 UTC, yudi-azvd approved these changes
Tudo certo

2022-02-24 23:20 UTC, yudi-azvd commented on docs/reunioes/02-02.md
> +    - Yudi Yamane
Não precisa de espaços antes do `-`

2022-02-26 01:01 UTC, AmandaNbr requested changes
As versões começam com 1.0 e não com 0.1
Colocar links para o perfil do integrante da equipe e para o artefato quando for citado

2022-02-26 01:02 UTC, AmandaNbr commented
Fora isso tudo ok!!

2022-02-26 03:56 UTC, yudi-azvd approved these changes

2022-02-26 03:56 UTC, yudi-azvd commented on docs/reunioes/17-02.md
> +| Documento de Resultado            | Yudi                                                         |
Sugestão: "Documento de Resultado/Priorização", porque o nome do documento foi mudado

2022-03-04 21:06 UTC, merged